language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
before_install:
  - gem update --system
  - gem install bundler
  - gem install rake
script:
  - bundle exec rspec spec/
bundler_args: --binstubs=./bundler_stubs
